https://jakevdp.github.io/PythonDataScienceHandbook/

## Numpy

* NumPy is a Python library.
* NumPy is used for working with arrays.
* NumPy is short for "Numerical Python".
* Lists in Python serve the same purpose as arrays, but they are slower to process.
* NumPy strives to provide array objects that are up to 50 times faster than typical Python lists.
* The array object in NumPy is named ndarray, and it comes with several helper methods that make working with ndarray.
* Arrays are often utilized in data science, where speed and resources are critical.

* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
* This behavior is called locality of reference in computer science.
* This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

### Creating Numpy Arrays with List

In [15]:
import numpy as np

# integer array:
np.array([1, 4, 2, 5, 3])



array([1, 4, 2, 5, 3])

In [16]:

#unlike Python lists, NumPy is constrained to arrays that all contain the same type. 
#If types do not match, NumPy will upcast if possible

np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [19]:
#If we want to explicitly set the data type of the resulting array, we can use the dtype keyword

np.array([3.14, 2, 3, 4], dtype='int')

array([3, 2, 3, 4])

In [23]:
#Finally, unlike Python lists, 
#NumPy arrays can explicitly be multi-dimensional; 
#here's one way of initializing a multidimensional array using a list of lists
2,5
4,7

ar = np.array([range(i, i + 3) for i in [2, 4, 6]])


ar.ndim
ar

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Numpy Arrays from Scratch

In [14]:
#Especially for larger arrays, 
#it is more efficient to create arrays from scratch 
#using routines built into NumPy. Here are several examples

In [24]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [26]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [14]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))


array([[0.41339935, 0.3354023 , 0.16427381],
       [0.51627815, 0.26013539, 0.35846064],
       [0.57670808, 0.25748775, 0.78995719]])

In [27]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.38742991, -0.17112274,  0.46926784],
       [ 1.93146889,  0.77906277,  0.91966708],
       [-0.57982161, -1.25247021,  0.88970938]])

In [22]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 1, 7],
       [2, 5, 8],
       [9, 4, 9]])

In [28]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])