## Numpy Attributes

In [29]:
import numpy as np
np.random.seed(34543)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [30]:
x1

array([6, 5, 1, 9, 6, 2])

In [3]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)
print(x1)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6
[5 0 3 3 7 9]


In [4]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print(x2)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [6]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print(x3)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [5]:
# dtype - the data type of the array 
# itemsize - which lists the size
# nbytes - which lists the total size
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


In [9]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

#ewarr = arr.astype('i')
newarr = arr.astype(int)
#newarr = arr.astype(float)

print(newarr)

#print(newarr)
#print(newarr.dtype)

[1 2 3]
