## Indexing Numpy Arrays

In [8]:
import numpy as np

### 1-dimentional Arrays

In [9]:
#just as with Python lists:
x = np.array([5, 0, 3, 3, 7, 9])
print(x[2])

3


### 2-Dimentional Arrays

In [10]:
x1 = np.random.randint(0,20,(3,3))
print(x1)

[[10 16  4]
 [ 7 10 17]
 [ 1 10 10]]


In [14]:
x1[1, 2]

17

In [15]:
#Assign new value with indexing
x1[1, 0] = 12
x1

array([[10, 16,  4],
       [12, 10, 17],
       [ 1, 10, 10]])

### 3-Dimentional Arrays

In [16]:
x2 = np.random.randint(0,20,(3,4,2))
print(x2)

[[[11 10]
  [15 17]
  [ 9  8]
  [14 16]]

 [[ 8  0]
  [ 7 10]
  [10 15]
  [ 5 17]]

 [[ 8  9]
  [15  9]
  [ 2 11]
  [15 10]]]


In [17]:
x2[0,2,1]

8

## Slicing Numpy Arrays

### 1-Dimentional Arrays

In [ ]:
#We can use the same syntax used for list
# x[start:stop:step]

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

### 2-Dimentional Arrays

In [19]:
x1 = np.random.randint(0,20,(3,3))
print(x1)

[[12 12 17]
 [ 2 13  3]
 [18  0 10]]


In [21]:
x1[:2, :]  # two rows, three columns

array([[12, 12, 17],
       [ 2, 13,  3]])

In [23]:
x1[0::2, 1::]

array([[12, 17],
       [ 0, 10]])

In [51]:
x1[:,0]

array([ 3, 15,  6])

In [25]:
x1[2,:]

array([18,  0, 10])

[ 1 42  3  4  5]
[1 2 3 4 5]


[42  2  3  4  5]
[42  2  3  4  5]
