## Numpy copy vs view

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr[0:]
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[1] = 42

print(arr)
print(x)

[ 1 42  3  4  5]
[1 2 3 4 5]
