## Reshaping arrays

* Reshaping means changing the shape of an array.
* The shape of an array is the number of elements in each dimension.
* By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#newarr = arr.reshape(4, 3)
#newarr = arr.reshape(2, 3, 2)
newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [4]:
# you can reshape an array if the no. of elements matching with the expected new dimentions
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
#newarr = arr.reshape(2, 3, 2)
#newarr = arr.reshape(3, 3)
print(arr)
print(newarr)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
# reshaping is not actually creating a new array - its a view - any changes in base array will reflect in new one
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
#newarr = arr.reshape(2, 3, 2)
#newarr = arr.reshape(3, 3)
print('before change:\n')
print(arr)
print(newarr)

arr[0]=23
newarr[2,0]=12

print('\nafter change:\n')
print(arr)
print(newarr)


before change:

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

after change:

[23  2  3  4  5  6 12  8  9 10 11 12]
[[23  2  3]
 [ 4  5  6]
 [12  8  9]
 [10 11 12]]


## Flattening Arrays

In [16]:
import numpy as np

#arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr.ndim)

newarr = arr.reshape(-1)

print(newarr)

3
[1 2 3 4 5 6 1 2 3 4 5 6]
