## Iterating Numpy Arrays


In [2]:
# Iterating 1-D Array
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [4]:
# Iterating 2-D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [5]:
# Iterating 3-D Array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()

* In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [6]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### Iterating with different steps

In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])

print(arr)

for x in np.nditer(arr[:, ::2]):
  print(x)

[[1 2 3 4]
 [5 6 7 8]]
1
3
5
7


### Enumerated Iteration Using ndenumerate()

* Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [9]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
