## Joining Numpy Arrays

* Joining means putting contents of two or more arrays in a single array.
* In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
* We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [16]:
#axis = 0 means row - vertical axis
#axis = 1 means columns - horizondal axis

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [21]:
# The number of elements should be equal on the axis other than the axis on which concat 

import numpy as np

arr1 = np.array([[1, 2, 5], 
                 [3, 4, 6]])

arr2 = np.array([[5, 6], 
                 [7, 8]]) 

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

## Joining Arrays Using Stack Functions

* Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
* We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
* We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [24]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])


arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [26]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
#NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

import numpy as np

arr1 = np.array([1, 2, 3, 33])

arr2 = np.array([4, 5, 6, 44])

arr = np.dstack((arr1, arr2))

print(arr.ndim)

3
