## Numpy Split Arrays

* Splitting is reverse operation of Joining.
* Joining merges multiple arrays into one and Splitting breaks one array into multiple.
* We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

### Splitting 1D Arrays

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

#The return value of the array_split() method is an array containing each of the split as an array.
#If you split an array into 3 arrays, you can access them from the result just like any array element:
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[5 6]


In [18]:
# If the array has less elements than required, it will adjust from the end accordingly.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

# Note: We also have the method split() available but it will not adjust the elements when elements are less in source array 
# for splitting like in example above, array_split() worked properly but split() would fail.

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Splitting 2D Arrays

In [5]:
import numpy as np

arr1 = np.array([[1, 2], 
                 [3, 4], 
                 [5, 6], 
                 [7, 8], 
                 [9, 10], 
                 [11, 12]])

arr2 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]])


newarr = np.array_split(arr2, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [12]:
# In addition, you can specify which axis you want to do the split around.
# The example below also returns three 2-D arrays, but they are split along  (axis=1).

import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=0)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [19]:
#hsplit() / vsplit()
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(arr)
#newarr = np.hsplit(arr, 3)
newarr = np.vsplit(arr, 3)


print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
