## Numpy Searching

* You can search an array for a certain value, and return the indexes that get a match.
* To search an array, use the where() method.

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

#The example above will return a tuple: (array([3, 5, 6],)

#Which means that the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


### Search Sorted

* There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [18]:
#The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next valu

import numpy as np

arr = np.array([ 6, 8, 9, 5])

x = np.searchsorted(arr, 10)

print(x)

4


In [22]:
# side option can be used if you need to search from right

import numpy as np

arr = np.array([6, 7, 8, 9, 10])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


### Multiple Values

* To search for more than one value, use an array with the specified values.

In [23]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
