## Sorting Numpy Array

* Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
* The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [8]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

# This method returns a copy of the array, leaving the original array unchanged.

[0 1 2 3]


In [1]:
#Alphabetic sorting

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [2]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

#0 1 1

[False  True  True]


In [3]:
#2D Array sorting 
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
