https://jakevdp.github.io/PythonDataScienceHandbook/

## Numpy

* NumPy is a Python library.
* NumPy is used for working with arrays.
* NumPy is short for "Numerical Python".
* Lists in Python serve the same purpose as arrays, but they are slower to process.
* NumPy strives to provide array objects that are up to 50 times faster than typical Python lists.
* The array object in NumPy is named ndarray, and it comes with several helper methods that make working with ndarray simple.
* Arrays are often utilized in data science, where speed and resources are critical.

### Creating Numpy Arrays with List

In [6]:
import numpy as np

# integer array:
np.array([1, 4, 2, 5, 3])



array([1, 4, 2, 5, 3])

In [7]:

#unlike Python lists, NumPy is constrained to arrays that all contain the same type. 
#If types do not match, NumPy will upcast if possible

np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
#If we want to explicitly set the data type of the resulting array, we can use the dtype keyword

np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [11]:
#Finally, unlike Python lists, 
#NumPy arrays can explicitly be multi-dimensional; 
#here's one way of initializing a multidimensional array using a list of lists

np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Numpy Arrays from Scratch

In [14]:
#Especially for larger arrays, 
#it is more efficient to create arrays from scratch 
#using routines built into NumPy. Here are several examples

In [15]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.39686318, 0.37295804, 0.54747189],
       [0.97772882, 0.98557554, 0.02180668],
       [0.98220421, 0.02560442, 0.07908468]])

In [21]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.20423211,  0.13920573, -0.21872116],
       [-0.78797444, -0.20407351, -0.56343836],
       [ 0.16373517, -1.16198081,  2.27558649]])

In [22]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 1, 7],
       [2, 5, 8],
       [9, 4, 9]])

In [23]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])