## Joining Numpy Arrays

* Joining means putting contents of two or more arrays in a single array.
* In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
* We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [15]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[1 2 3 4 5 6]


In [5]:
# The number of elements should be equal on the axis other than the axis on which concat 

import numpy as np

arr1 = np.array([[1, 2], 
                 [3, 4]])

arr2 = np.array([[5, 6], 
                 [7, 8]]) 

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [8]:
# The number of elements should be equal on the axis other than the concatenation axis

import numpy as np

arr1 = np.array([[1, 2], 
                 [3, 4]])

arr2 = np.array([[5, 6], 
                 [7, 8],
                 [9, 10]]) 

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

## Joining Arrays Using Stack Functions

* Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
* We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
* We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [21]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [18]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [19]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [31]:
import numpy as np

arr1 = np.array([1, 2, 3, 33])

arr2 = np.array([4, 5, 6, 44])

arr = np.dstack((arr1, arr2))

print(arr)

[[[ 1  4]
  [ 2  5]
  [ 3  6]
  [33 44]]]
